# Generated by Django 3.2.25 on 2025-03-11 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_equipment_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='hourly_rate',
            new_name='daily_rate',
        ),
    ]
