# Generated by Django 3.2.25 on 2025-03-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_rename_hourly_rate_vehicle_daily_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='book_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirm', 'Confirm'), ('Cancelled', 'Cancelled')], default='Pending ', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Pending ', max_length=20),
        ),
    ]
